### PR TITLE
Add synthwave theme

### PR DESCRIPTION
**Pull request by sudoyasir**

### CODE REVIEW

**Comment by AyushSaini00** [comment]
hey @yasir2002 can you please also add a screenshot of the theme?

**Comment by sudoyasir** [comment]
Here screenshot of Synthwave:
image

**Comment by AyushSaini00** [comment]
LGTM! Thanks for contributing @yasir2002 🎉

**Review by AyushSaini00 — COMMENTED** [review]
lgtm

**Comment by sudoyasir** [comment]
Thank you so much @AyushSaini00 for accepting my PR, It was a great experience contributing to this open source project. I'm thrilled to be part of this collabrative community and I look forward to contributing more in future. Cheers! 🚀

**Pull request merged**
