### PR TITLE
add dracula and nord themes

### PR DESCRIPTION
**Pull request by chris--jones**
For #2 

I've added a couple of my favourite themes: [dracula](https://draculatheme.com/) and [nord](https://www.nordtheme.com/) (both light and dark)

Dracula:
image

Nord Dark (nord-dark):
image

Nord Light (nord-light):
image

### CODE REVIEW

**Comment by chris--jones** [comment]
I also played around with the idea of a tertiary (third colour) that falls back to secondary colour if not provided:
image
image

**Comment by chris--jones** [comment]
hey @AyushSaini00, any feedback or changes you'd like me to make?

Note: I haven't included the tertiary colour stuff as was awaiting your feedback on if you wanted that functionality or not.

**Comment by AyushSaini00** [comment]
@chris--jones can you please use the hex value for the white color as well? Also, please make sure that the hex codes are in all caps.

**Comment by chris--jones** [comment]
Ah yes, I noticed and fixed the white, but forgot about the uppercase bit - sorted it now.

**Comment by AyushSaini00** [comment]
Thank you for contributing @chris--jones 🎉

**Pull request merged**
